### ISSUE TITLE
Create `WorkflowCollectionTagType` model.

### ISSUE THREAD

**Issue by eikonomega** [eikonomega/django-workflow-system#13]
Tags represent metadata assigned to collections. We want to allow
multiple types of tags to allow different sets of metadata to be 
attached to a given collection.

Assignees: 
Labels: enhancement

**Comment by eikonomega** [comment]
```
collection

tags: [
  {tagtype: string, value: string},
  {tagtype: string, value: string},
]

```

**Comment by bfox6** [comment]
**Model Definitions**
Inherit from abstractmodal
id : uuid
type : char(50)
