### ISSUE TITLE
Anywhere we have `Attributes` documented like this move to `help_text` on the various model fields.

### ISSUE THREAD

**Issue by eikonomega** [eikonomega/django-workflow-system#40]
https://github.com/crcresearch/django-workflow-system/blob/64920387483a9fd12f2474718bedab726d4634e8/workflows/models/workflow.py#L13-L29

**Comment by bfox6** [comment]
I moved all the docstring attributes to help_text but there are many models that need help_text written still.

**Comment by eikonomega** [comment]
Thanks @bfox6. I will create a follow-up issue.
