### ISSUE TITLE
All top-level URLs should be listed here.

### ISSUE THREAD

**Issue by eikonomega** [eikonomega/django-workflow-system#44]
Any URL that is an immediate child of `workflow-system` should be present here.

![image](https://user-images.githubusercontent.com/415939/112073879-546a6900-8b4b-11eb-9b03-9128de1702f8.png)

**Comment by bfox6** [comment]
Users (add)
    -> Users top level things (assignments, engagements, recommendations)
Workflows
    -> Steps

**Comment by eikonomega** [comment]
@bfox6 I think you've got this nailed. It's missing recommendations, but that is because that model hasn't been brought over yet.
