### ISSUE TITLE
Warn users on app load if authentication settings have not been set.

### ISSUE THREAD

**Issue by eikonomega** [eikonomega/django-workflow-system#45]
https://www.django-rest-framework.org/api-guide/authentication/#setting-the-authentication-scheme

**Comment by bfox6** [comment]
So when app is started print out a message telling the dev that if they don't set the auth settings it will use the default basic auth

**Comment by eikonomega** [comment]
I dug into this a little bit more... @bfox6 

I think we need to perform 3 checks...

```
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}
```

1. Does `REST_FRAMEWORK` exist in settings?
2. Does it contain a `DEFAULT_AUTHENTICATION_CLASSES` key?
3. Does it contain a `DEFAULT_PERMISSION_CLASSES` key?

**Comment by eikonomega** [comment]
You can test this by commenting/un-commenting these settings in the test project.

**Comment by bfox6** [comment]
New project settings are on url_config branch
