### ISSUE TITLE
When an engagement is created/modified (saved), a search should be made for a matching assignment...

### ISSUE THREAD

**Issue by eikonomega** [eikonomega/django-workflow-system#59]
The assignment's foreign key back to engagement should be populated if there is match.

**Comment by bfox6** [comment]
An engagement is saved -> search in this engagement's collection for an assignment that is "ASSIGNED" and has no 'engagement' FK -> If I find this assignment then update that assignment to point to the engagement -> If I don't find it then do nothing (continue)
